# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Finopsly < Formula
  desc "Shift-left AWS infrastructure cost estimation for Terraform"
  homepage "https://finopsly.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_darwin_amd64.tar.gz"
      sha256 "1b297ee9ad26e443a1e5d222e4baee72b1ea8fffdad76561822a7cd1c7654014"

      define_method(:install) do
        bin.install "finopsly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_darwin_arm64.tar.gz"
      sha256 "d2d9a62622e2a6a36c1dda240a3101e069e9389a3c91ac0987bd64a936879ca3"

      define_method(:install) do
        bin.install "finopsly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_linux_amd64.tar.gz"
      sha256 "d04d395585c7241e1f02af80f49bd9771ad6efe8f7637fb429eaf54d94675e04"
      define_method(:install) do
        bin.install "finopsly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_linux_arm64.tar.gz"
      sha256 "75036d281901460ff78c5aa2c1c13960a01f419127a9660b5b033083f20c3cf0"
      define_method(:install) do
        bin.install "finopsly"
      end
    end
  end
end
