# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Finopsly < Formula
  desc "Shift-left AWS infrastructure cost estimation for Terraform"
  homepage "https://finopsly.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_darwin_amd64.tar.gz"
      sha256 "de9bb933c58e5ce1b3ec7c53af8e1b4d0ea64961743cd2b6ea2c4b09620aa583"

      define_method(:install) do
        bin.install "finopsly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_darwin_arm64.tar.gz"
      sha256 "f466d38587d41449f7ae4c1205c35f936eca114dd59d1ce87029abc797f1912e"

      define_method(:install) do
        bin.install "finopsly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_linux_amd64.tar.gz"
      sha256 "89520f05e6cacf5c65726733243e7d2a368151aa5913039ce581afb3c7e94114"
      define_method(:install) do
        bin.install "finopsly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finopsly/finopsly-pulse-cli/releases/download/v1.0.0/finopsly_linux_arm64.tar.gz"
      sha256 "18a58a37984a29f927e64501a154a0c5b31648336d708697eacb14c7df1e6003"
      define_method(:install) do
        bin.install "finopsly"
      end
    end
  end
end
